spring:
  application:
    name: producer-app
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    alibaba:
      seata:
        tx-service-group: tx_seata_group
    nacos:
      config:
        server-addr: ${config-server.server-addr}
  #============================| Sharding-JDBC |============================
  shardingsphere:
    # 数据源
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql.localhost:3306/db_springcloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: hocgin
    # 数据分片
    sharding:
      binding-tables: t_producer
      tables:
        t_producer:
          actual-data-nodes: ds0.t_producer_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_producer_$->{id % 2}

#debug: true
server:
  port: 8082
dubbo:
  scan:
    base-packages: in.hocg
  protocol:
    name: dubbo
    port: -1
  registry:
    address: ${registry.address}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  consumer:
    check: false

#============================| Seata |============================
seata:
  enabled: true
  tx-service-group: tx_seata_group
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      server-addr: nacos.localhost:8848
      namespace:
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: nacos.localhost:8848
      namespace:
      group: SEATA_GROUP